words: 看着,望着,抚摸着,欣赏,凝视

server:
  port: 18881
#  port: ${PORT:${SERVER_PORT:0}}
#  这个的意思是随机指定个没使用的端口


eureka:
#  password: password
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

#  默认统计心跳失败的比例在15分钟之内是否低于85%
#  instance:
#    lease-renewal-interval-in-seconds: 2
#    lease-expiration-duration-in-seconds: 4